package forceitembattle.manager;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import forceitembattle.ForceItemBattle;
import forceitembattle.settings.GameSetting;
import forceitembattle.util.DescriptionItem;
import lombok.Getter;
import lombok.Setter;
import org.bukkit.ChatColor;
import org.bukkit.Material;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class ItemDifficultiesManager {

    private final ForceItemBattle plugin;

    @Getter
    private final List<Material> netherItems;
    @Getter
    private final List<Material> endItems;
    private final List<Material> veryLateItems;

    @Getter
    private HashMap<Material, DescriptionItem> descriptionItems;

    /**
     * Chat and tablist use smaller icons.
     */
    private Map<Material, String> smallIconUnicodes;
    /**
     * Bossbar is using bigger icons.
     */
    private Map<Material, String> bigIconUnicodes;

    public void setupStates() {
        State.EARLY.setUnlockedAtPercentage(0);
        State.MID.setUnlockedAtPercentage(11.11);
        State.LATE.setUnlockedAtPercentage(28.88);
    }

    public List<Material> getAvailableItems() {
        int timeLeft = this.plugin.getTimer().getTimeLeft();
        int totalDuration = this.plugin.getGamemanager().getGameDuration();
        List<Material> items = new ArrayList<>();

        int elapsedTime = (totalDuration - timeLeft) / 60;

        for (State state : State.VALUES) {
            int unlockTime = (int) Math.round((totalDuration * (state.getUnlockedAtPercentage() / 100)) / 60);
            if (elapsedTime < unlockTime) {
                continue;
            }

            items.addAll(state.getItems());
        }

        return items;
    }

    public Set<Material> getOverworldItems() {
        return Stream.of(State.EARLY.getItems(), State.MID.getItems(), State.LATE.getItems())
                .flatMap(List::stream)
                .filter(item -> !this.netherItems.contains(item) && !this.endItems.contains(item))
                .collect(Collectors.toSet());
    }

    public Set<Material> getAllItems() {
        return Stream.of(State.EARLY.getItems(), State.MID.getItems(), State.LATE.getItems())
                .flatMap(List::stream)
                .collect(Collectors.toSet());
    }

    public Material generateRandomMaterial() {
        Random random = new Random();
        List<Material> items = getAvailableItems();

        filterDisabledItems(items);

        return items.get(random.nextInt(items.size()));
    }

    public boolean isItemInDescriptionList(Material material) {
        return this.getDescriptionItems().containsKey(material);
    }

    public boolean itemHasDescription(Material material) {
        return this.getDescriptionItems().get(material) != null;
    }

    public List<String> getDescriptionItemLines(Material material) {
        List<String> lines = null;
        if (this.isItemInDescriptionList(material)) {
            if(this.itemHasDescription(material)) {
                lines = this.getDescriptionItems().get(material)
                        .lines()
                        .stream()
                        .map(line -> ChatColor.translateAlternateColorCodes('&', line))
                        .toList();
                // lines = this.getDescriptionItems().get(material).lines();
            } else {
                throw new NullPointerException(material.name() + " does not have a description");
            }
        }
        return lines;
    }

    public String getUnicodeFromMaterial(boolean smallIcon, Material material) {
        return this.getItemUnicodes(smallIcon).getOrDefault(material, "NULL");
    }

    public Map<Material, String> getItemUnicodes(boolean smallIcon) {
        if (smallIcon) {
            if (smallIconUnicodes == null) {
                smallIconUnicodes = readItemUnicodes(true);
            }

            return smallIconUnicodes;
        }

        if (bigIconUnicodes == null) {
            bigIconUnicodes = readItemUnicodes(false);
        }

        return bigIconUnicodes;
    }

    /**
     * Method to read the unicodes from the file.
     */
    private Map<Material, String> readItemUnicodes(boolean smallIcon) {
        Map<Material, String> itemsUnicode = new HashMap<>();
        File file = new File(this.plugin.getDataFolder(), "unicodeItems.json");

        if (!file.exists()) {
            this.plugin.getLogger().warning("`unicodeItems.json` does not exist, not using custom icons");
            return new HashMap<>();
        }

        try (FileReader fileReader = new FileReader(file)) {
            Gson gson = new Gson();
            Type mapType = new TypeToken<Map<String, String>[]>(){}.getType();
            Map<String, String>[] items = gson.fromJson(fileReader, mapType);

            for (Map<String, String> entry : items) {
                String materialName = entry.get("material");
                String unicode = entry.get("unicode");

                if (materialName != null && unicode != null) {
                    if (smallIcon && materialName.contains("_tabChat")) {
                        Material material = Material.getMaterial(materialName.replace("_tabChat", ""));
                        if (material != null) {
                            itemsUnicode.put(material, unicode);
                        }

                    } else if (!smallIcon && !materialName.contains("_tabChat")) {
                        Material material = Material.getMaterial(materialName);
                        if (material != null) {
                            itemsUnicode.put(material, unicode);
                        }
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return itemsUnicode;
    }

    /**
     * Filter out items disabled by the settings
     */
    private void filterDisabledItems(Collection<Material> items) {
        if (!plugin.getSettings().isSettingEnabled(GameSetting.HARD)) {
            this.netherItems.forEach(items::remove);

            this.veryLateItems.forEach(items::remove);

        } else if (!plugin.getSettings().isSettingEnabled(GameSetting.EXTREME)) {
            this.veryLateItems.forEach(items::remove);
        }

        if (!plugin.getSettings().isSettingEnabled(GameSetting.END)) {
            this.endItems.forEach(items::remove);
        }
    }

    public boolean itemInList(Material material) {
        return this.getAvailableItems().contains(material);
    }

    public boolean itemInAllLists(Material material) {
        return this.getAllItems().contains(material);
    }


    public ItemDifficultiesManager(ForceItemBattle forceItemBattle) {
        this.plugin = forceItemBattle;

        this.descriptionItems = new HashMap<>();
        this.netherItems = List.of(
                Material.ANCIENT_DEBRIS,
                Material.BASALT,
                Material.BLACKSTONE,
                Material.BLACKSTONE_SLAB,
                Material.BLACKSTONE_STAIRS,
                Material.BLACKSTONE_WALL,
                Material.BLAZE_POWDER,
                Material.BLAZE_ROD,
                Material.CHISELED_POLISHED_BLACKSTONE,
                Material.CHISELED_QUARTZ_BLOCK,
                Material.COMPARATOR,
                Material.CRACKED_POLISHED_BLACKSTONE_BRICKS,
                Material.CRIMSON_BUTTON,
                Material.CRIMSON_DOOR,
                Material.CRIMSON_FENCE,
                Material.CRIMSON_FENCE_GATE,
                Material.CRIMSON_FUNGUS,
                Material.CRIMSON_HANGING_SIGN,
                Material.CRIMSON_HYPHAE,
                Material.CRIMSON_NYLIUM,
                Material.CRIMSON_PLANKS,
                Material.CRIMSON_PRESSURE_PLATE,
                Material.CRIMSON_ROOTS,
                Material.CRIMSON_SIGN,
                Material.CRIMSON_SLAB,
                Material.CRIMSON_STAIRS,
                Material.CRIMSON_STEM,
                Material.CRIMSON_TRAPDOOR,
                Material.DAYLIGHT_DETECTOR,
                Material.ENDER_EYE,
                Material.SPLASH_POTION,
                Material.GHAST_TEAR,
                Material.GILDED_BLACKSTONE,
                Material.GLOWSTONE,
                Material.GLOWSTONE_DUST,
                Material.KNOWLEDGE_BOOK, // Antimatter Depths Locator
                Material.MAGMA_CREAM,
                Material.MUSIC_DISC_PIGSTEP,
                Material.NETHER_GOLD_ORE,
                Material.NETHER_QUARTZ_ORE,
                Material.NETHER_SPROUTS,
                Material.NETHER_WART,
                Material.NETHER_WART_BLOCK,
                Material.NETHERITE_AXE,
                Material.NETHERITE_BLOCK,
                Material.NETHERITE_BOOTS,
                Material.NETHERITE_CHESTPLATE,
                Material.NETHERITE_HELMET,
                Material.NETHERITE_HOE,
                Material.NETHERITE_INGOT,
                Material.NETHERITE_LEGGINGS,
                Material.NETHERITE_PICKAXE,
                Material.NETHERITE_SCRAP,
                Material.NETHERITE_SHOVEL,
                Material.NETHERITE_SWORD,
                Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE,
                Material.PIGLIN_BANNER_PATTERN,
                Material.POLISHED_BLACKSTONE,
                Material.POLISHED_BLACKSTONE_BRICK_SLAB,
                Material.POLISHED_BLACKSTONE_BRICK_STAIRS,
                Material.POLISHED_BLACKSTONE_BRICK_WALL,
                Material.POLISHED_BLACKSTONE_BRICKS,
                Material.POLISHED_BLACKSTONE_BUTTON,
                Material.POLISHED_BLACKSTONE_SLAB,
                Material.POLISHED_BLACKSTONE_STAIRS,
                Material.POLISHED_BLACKSTONE_WALL,
                Material.QUARTZ_BLOCK,
                Material.QUARTZ_BRICKS,
                Material.QUARTZ_PILLAR,
                Material.QUARTZ_SLAB,
                Material.QUARTZ_STAIRS,
                Material.RED_NETHER_BRICK_SLAB,
                Material.RED_NETHER_BRICK_STAIRS,
                Material.RED_NETHER_BRICK_WALL,
                Material.RED_NETHER_BRICKS,
                Material.REDSTONE_LAMP,
                Material.RESPAWN_ANCHOR,
                Material.RIB_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.SHROOMLIGHT,
                Material.SKULL_BANNER_PATTERN,
                Material.SMOOTH_QUARTZ,
                Material.SMOOTH_QUARTZ_SLAB,
                Material.SMOOTH_QUARTZ_STAIRS,
                Material.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.SOUL_CAMPFIRE,
                Material.SOUL_SAND,
                Material.SOUL_SOIL,
                Material.SOUL_LANTERN,
                Material.SPECTRAL_ARROW,
                Material.STRIPPED_CRIMSON_HYPHAE,
                Material.STRIPPED_CRIMSON_STEM,
                Material.STRIPPED_WARPED_HYPHAE,
                Material.STRIPPED_WARPED_STEM,
                Material.TWISTING_VINES,
                Material.WARPED_BUTTON,
                Material.WARPED_DOOR,
                Material.WARPED_FENCE,
                Material.WARPED_FUNGUS,
                Material.WARPED_FUNGUS_ON_A_STICK,
                Material.WARPED_HANGING_SIGN,
                Material.WARPED_HYPHAE,
                Material.WARPED_NYLIUM,
                Material.WARPED_PLANKS,
                Material.WARPED_PRESSURE_PLATE,
                Material.WARPED_ROOTS,
                Material.WARPED_SIGN,
                Material.WARPED_SLAB,
                Material.WARPED_STAIRS,
                Material.WARPED_STEM,
                Material.WARPED_TRAPDOOR,
                Material.WARPED_WART_BLOCK,
                Material.WEEPING_VINES,
                Material.WITHER_SKELETON_SKULL
        );

        this.endItems = List.of(
                Material.END_STONE,
                Material.END_STONE_BRICK_SLAB,
                Material.END_STONE_BRICK_STAIRS,
                Material.END_STONE_BRICK_WALL,
                Material.END_STONE_BRICKS,
                Material.PURPUR_BLOCK,
                Material.PURPUR_PILLAR,
                Material.PURPUR_SLAB,
                Material.PURPUR_STAIRS,
                Material.CHORUS_FRUIT,
                Material.CHORUS_FLOWER,
                Material.DRAGON_HEAD,
                Material.END_ROD,
                Material.ELYTRA,
                Material.SHULKER_SHELL,
                Material.SHULKER_BOX,
                Material.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.WHITE_SHULKER_BOX,
                Material.ORANGE_SHULKER_BOX,
                Material.MAGENTA_SHULKER_BOX,
                Material.LIGHT_BLUE_SHULKER_BOX,
                Material.YELLOW_SHULKER_BOX,
                Material.LIME_SHULKER_BOX,
                Material.PINK_SHULKER_BOX,
                Material.GRAY_SHULKER_BOX,
                Material.LIGHT_GRAY_SHULKER_BOX,
                Material.CYAN_SHULKER_BOX,
                Material.POPPED_CHORUS_FRUIT,
                Material.PURPLE_SHULKER_BOX,
                Material.BLUE_SHULKER_BOX,
                Material.BROWN_SHULKER_BOX,
                Material.GREEN_SHULKER_BOX,
                Material.RED_SHULKER_BOX,
                Material.BLACK_SHULKER_BOX
        );

        // list contains hard items that are very unrealistic to obtain in 45 min
        this.veryLateItems = List.of(
                Material.ARCHER_POTTERY_SHERD,
                Material.CALIBRATED_SCULK_SENSOR,
                Material.COPPER_ORE,
                Material.DEEPSLATE_COPPER_ORE,
                Material.DEEPSLATE_DIAMOND_ORE,
                Material.DEEPSLATE_EMERALD_ORE,
                Material.DEEPSLATE_GOLD_ORE,
                Material.DEEPSLATE_IRON_ORE,
                Material.DEEPSLATE_LAPIS_ORE,
                Material.DEEPSLATE_REDSTONE_ORE,
                Material.DIAMOND_ORE,
                Material.DISC_FRAGMENT_5,
                Material.ECHO_SHARD,
                Material.EMERALD_ORE,
                Material.END_CRYSTAL,
                Material.EYE_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.FLOW_BANNER_PATTERN,
                Material.GLOBE_BANNER_PATTERN,
                Material.GOLD_ORE,
                Material.GUSTER_BANNER_PATTERN,
                Material.IRON_ORE,
                Material.LAPIS_ORE,
                Material.MINER_POTTERY_SHERD,
                Material.MUSIC_DISC_CREATOR,
                Material.MUSIC_DISC_PRECIPICE,
                Material.NETHERITE_AXE,
                Material.NETHERITE_BLOCK,
                Material.NETHERITE_BOOTS,
                Material.NETHERITE_CHESTPLATE,
                Material.NETHERITE_HELMET,
                Material.NETHERITE_HOE,
                Material.NETHERITE_LEGGINGS,
                Material.NETHERITE_PICKAXE,
                Material.NETHERITE_SHOVEL,
                Material.NETHERITE_SWORD,
                Material.OMINOUS_BOTTLE,
                Material.OMINOUS_TRIAL_KEY,
                Material.PRIZE_POTTERY_SHERD,
                Material.REDSTONE_ORE,
                Material.SKULL_POTTERY_SHERD,
                Material.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.TOTEM_OF_UNDYING,
                Material.VEX_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.WARD_ARMOR_TRIM_SMITHING_TEMPLATE
        );


        // Ideally these should be in the enum constructors, but here is fine, I guess.
        State.EARLY.setItems(List.of(
                Material.ACACIA_BOAT,
                Material.ACACIA_BUTTON,
                Material.ACACIA_CHEST_BOAT,
                Material.ACACIA_DOOR,
                Material.ACACIA_FENCE,
                Material.ACACIA_FENCE_GATE,
                Material.ACACIA_HANGING_SIGN,
                Material.ACACIA_LEAVES,
                Material.ACACIA_LOG,
                Material.ACACIA_PLANKS,
                Material.ACACIA_PRESSURE_PLATE,
                Material.ACACIA_SAPLING,
                Material.ACACIA_SIGN,
                Material.ACACIA_SLAB,
                Material.ACACIA_STAIRS,
                Material.ACACIA_TRAPDOOR,
                Material.ACACIA_WOOD,
                Material.ACTIVATOR_RAIL,
                Material.AMETHYST_BLOCK,
                Material.AMETHYST_SHARD,
                Material.ANDESITE,
                Material.ANDESITE_SLAB,
                Material.ANDESITE_STAIRS,
                Material.ANDESITE_WALL,
                Material.APPLE,
                Material.ARMADILLO_SCUTE,
                Material.ARMOR_STAND,
                Material.ARROW,
                Material.AZURE_BLUET,
                Material.BAKED_POTATO,
                Material.BAMBOO,
                Material.BAMBOO_BLOCK,
                Material.BAMBOO_BUTTON,
                Material.BAMBOO_CHEST_RAFT,
                Material.BAMBOO_DOOR,
                Material.BAMBOO_FENCE,
                Material.BAMBOO_FENCE_GATE,
                Material.BAMBOO_HANGING_SIGN,
                Material.BAMBOO_MOSAIC,
                Material.BAMBOO_MOSAIC_SLAB,
                Material.BAMBOO_MOSAIC_STAIRS,
                Material.BAMBOO_PLANKS,
                Material.BAMBOO_PRESSURE_PLATE,
                Material.BAMBOO_RAFT,
                Material.BAMBOO_SIGN,
                Material.BAMBOO_SLAB,
                Material.BAMBOO_STAIRS,
                Material.BAMBOO_TRAPDOOR,
                Material.BARREL,
                Material.BEEF,
                Material.BELL,
                Material.BIRCH_BOAT,
                Material.BIRCH_BUTTON,
                Material.BIRCH_CHEST_BOAT,
                Material.BIRCH_DOOR,
                Material.BIRCH_FENCE,
                Material.BIRCH_FENCE_GATE,
                Material.BIRCH_HANGING_SIGN,
                Material.BIRCH_LEAVES,
                Material.BIRCH_LOG,
                Material.BIRCH_PLANKS,
                Material.BIRCH_PRESSURE_PLATE,
                Material.BIRCH_SAPLING,
                Material.BIRCH_SIGN,
                Material.BIRCH_SLAB,
                Material.BIRCH_STAIRS,
                Material.BIRCH_TRAPDOOR,
                Material.BIRCH_WOOD,
                Material.BLACK_BANNER,
                Material.BLACK_BED,
                Material.BLACK_CARPET,
                Material.BLACK_CONCRETE,
                Material.BLACK_CONCRETE_POWDER,
                Material.BLACK_DYE,
                Material.BLACK_GLAZED_TERRACOTTA,
                Material.BLACK_STAINED_GLASS,
                Material.BLACK_STAINED_GLASS_PANE,
                Material.BLACK_TERRACOTTA,
                Material.BLACK_WOOL,
                Material.BLAST_FURNACE,
                Material.BLUE_BANNER,
                Material.BLUE_BED,
                Material.BLUE_CARPET,
                Material.BLUE_CONCRETE,
                Material.BLUE_CONCRETE_POWDER,
                Material.BLUE_DYE,
                Material.BLUE_GLAZED_TERRACOTTA,
                Material.BLUE_STAINED_GLASS,
                Material.BLUE_STAINED_GLASS_PANE,
                Material.BLUE_TERRACOTTA,
                Material.BLUE_WOOL,
                Material.BONE,
                Material.BONE_BLOCK,
                Material.BONE_MEAL,
                Material.BOOK,
                Material.BOOKSHELF,
                Material.BOWL,
                Material.BREAD,
                Material.BRICK,
                Material.BRICK_SLAB,
                Material.BRICK_STAIRS,
                Material.BRICK_WALL,
                Material.BRICKS,
                Material.BROWN_BANNER,
                Material.BROWN_BED,
                Material.BROWN_CARPET,
                Material.BROWN_CONCRETE,
                Material.BROWN_CONCRETE_POWDER,
                Material.BROWN_DYE,
                Material.BROWN_GLAZED_TERRACOTTA,
                Material.BROWN_MUSHROOM,
                Material.BROWN_STAINED_GLASS,
                Material.BROWN_STAINED_GLASS_PANE,
                Material.BROWN_TERRACOTTA,
                Material.BROWN_WOOL,
                Material.BRUSH,
                Material.BUCKET,
                Material.CALCITE,
                Material.CAMPFIRE,
                Material.CARROT,
                Material.CARROT_ON_A_STICK,
                Material.CARTOGRAPHY_TABLE,
                Material.CARVED_PUMPKIN,
                Material.CAULDRON,
                Material.CHAIN,
                Material.CHARCOAL,
                Material.CHEST,
                Material.CHEST_MINECART,
                Material.CHICKEN,
                Material.CHISELED_BOOKSHELF,
                Material.CHISELED_COPPER,
                Material.CHISELED_DEEPSLATE,
                Material.CHISELED_SANDSTONE,
                Material.CHISELED_STONE_BRICKS,
                Material.CHISELED_TUFF,
                Material.CHISELED_TUFF_BRICKS,
                Material.CLAY,
                Material.CLAY_BALL,
                Material.CLOCK,
                Material.COAL,
                Material.COAL_BLOCK,
                Material.COARSE_DIRT,
                Material.COBBLED_DEEPSLATE,
                Material.COBBLED_DEEPSLATE_SLAB,
                Material.COBBLED_DEEPSLATE_STAIRS,
                Material.COBBLED_DEEPSLATE_WALL,
                Material.COBBLESTONE,
                Material.COBBLESTONE_SLAB,
                Material.COBBLESTONE_STAIRS,
                Material.COBBLESTONE_WALL,
                Material.COCOA_BEANS,
                Material.COD,
                Material.COD_BUCKET,
                Material.COMPASS,
                Material.COMPOSTER,
                Material.COOKED_BEEF,
                Material.COOKED_CHICKEN,
                Material.COOKED_COD,
                Material.COOKED_MUTTON,
                Material.COOKED_PORKCHOP,
                Material.COOKED_SALMON,
                Material.COOKIE,
                Material.COPPER_BLOCK,
                Material.COPPER_DOOR,
                Material.COPPER_GRATE,
                Material.COPPER_INGOT,
                Material.CORNFLOWER,
                Material.CRACKED_DEEPSLATE_BRICKS,
                Material.CRACKED_DEEPSLATE_TILES,
                Material.CRACKED_STONE_BRICKS,
                Material.CRAFTER,
                Material.CRAFTING_TABLE,
                Material.CUT_COPPER,
                Material.CUT_COPPER_SLAB,
                Material.CUT_COPPER_STAIRS,
                Material.CUT_SANDSTONE,
                Material.CUT_SANDSTONE_SLAB,
                Material.DANDELION,
                Material.DARK_OAK_BOAT,
                Material.DARK_OAK_BUTTON,
                Material.DARK_OAK_CHEST_BOAT,
                Material.DARK_OAK_DOOR,
                Material.DARK_OAK_FENCE,
                Material.DARK_OAK_FENCE_GATE,
                Material.DARK_OAK_HANGING_SIGN,
                Material.DARK_OAK_LEAVES,
                Material.DARK_OAK_LOG,
                Material.DARK_OAK_PLANKS,
                Material.DARK_OAK_PRESSURE_PLATE,
                Material.DARK_OAK_SAPLING,
                Material.DARK_OAK_SIGN,
                Material.DARK_OAK_SLAB,
                Material.DARK_OAK_STAIRS,
                Material.DARK_OAK_TRAPDOOR,
                Material.DARK_OAK_WOOD,
                Material.DEEPSLATE,
                Material.DEEPSLATE_BRICK_SLAB,
                Material.DEEPSLATE_BRICK_STAIRS,
                Material.DEEPSLATE_BRICK_WALL,
                Material.DEEPSLATE_BRICKS,
                Material.DEEPSLATE_TILE_SLAB,
                Material.DEEPSLATE_TILE_STAIRS,
                Material.DEEPSLATE_TILE_WALL,
                Material.DEEPSLATE_TILES,
                Material.DETECTOR_RAIL,
                Material.DIAMOND,
                Material.DIAMOND_AXE,
                Material.DIAMOND_BOOTS,
                Material.DIAMOND_HOE,
                Material.DIAMOND_PICKAXE,
                Material.DIAMOND_SHOVEL,
                Material.DIAMOND_SWORD,
                Material.DIORITE,
                Material.DIORITE_SLAB,
                Material.DIORITE_STAIRS,
                Material.DIORITE_WALL,
                Material.DIRT,
                Material.DRIED_KELP,
                Material.DRIED_KELP_BLOCK,
                Material.DROPPER,
                Material.EMERALD,
                Material.FEATHER,
                Material.FERN,
                Material.FILLED_MAP,
                Material.FIREWORK_ROCKET,
                Material.FIREWORK_STAR,
                Material.FLETCHING_TABLE,
                Material.FLINT,
                Material.FLINT_AND_STEEL,
                Material.FLOWER_BANNER_PATTERN,
                Material.FLOWER_POT,
                Material.FURNACE,
                Material.FURNACE_MINECART,
                Material.GLASS,
                Material.GLASS_BOTTLE,
                Material.GLASS_PANE,
                Material.GLISTERING_MELON_SLICE,
                Material.GLOW_INK_SAC,
                Material.GLOW_ITEM_FRAME,
                Material.GLOW_LICHEN,
                Material.GOLD_BLOCK,
                Material.GOLD_INGOT,
                Material.GOLD_NUGGET,
                Material.GOLDEN_APPLE,
                Material.GOLDEN_AXE,
                Material.GOLDEN_BOOTS,
                Material.GOLDEN_CARROT,
                Material.GOLDEN_CHESTPLATE,
                Material.GOLDEN_HELMET,
                Material.GOLDEN_HOE,
                Material.GOLDEN_LEGGINGS,
                Material.GOLDEN_PICKAXE,
                Material.GOLDEN_SHOVEL,
                Material.GOLDEN_SWORD,
                Material.GRANITE,
                Material.GRANITE_SLAB,
                Material.GRANITE_STAIRS,
                Material.GRANITE_WALL,
                Material.GRAVEL,
                Material.GRAY_BANNER,
                Material.GRAY_BED,
                Material.GRAY_CARPET,
                Material.GRAY_CONCRETE,
                Material.GRAY_CONCRETE_POWDER,
                Material.GRAY_DYE,
                Material.GRAY_GLAZED_TERRACOTTA,
                Material.GRAY_STAINED_GLASS,
                Material.GRAY_STAINED_GLASS_PANE,
                Material.GRAY_TERRACOTTA,
                Material.GRAY_WOOL,
                Material.GRINDSTONE,
                Material.GUNPOWDER,
                Material.HAY_BLOCK,
                Material.HEAVY_WEIGHTED_PRESSURE_PLATE,
                Material.HOPPER,
                Material.HOPPER_MINECART,
                Material.INK_SAC,
                Material.IRON_AXE,
                Material.IRON_BARS,
                Material.IRON_BLOCK,
                Material.IRON_BOOTS,
                Material.IRON_CHESTPLATE,
                Material.IRON_DOOR,
                Material.IRON_HELMET,
                Material.IRON_HOE,
                Material.IRON_INGOT,
                Material.IRON_LEGGINGS,
                Material.IRON_NUGGET,
                Material.IRON_PICKAXE,
                Material.IRON_SHOVEL,
                Material.IRON_SWORD,
                Material.IRON_TRAPDOOR,
                Material.ITEM_FRAME,
                Material.JACK_O_LANTERN,
                Material.JUKEBOX,
                Material.JUNGLE_BOAT,
                Material.JUNGLE_BUTTON,
                Material.JUNGLE_CHEST_BOAT,
                Material.JUNGLE_DOOR,
                Material.JUNGLE_FENCE,
                Material.JUNGLE_FENCE_GATE,
                Material.JUNGLE_HANGING_SIGN,
                Material.JUNGLE_LEAVES,
                Material.JUNGLE_LOG,
                Material.JUNGLE_PLANKS,
                Material.JUNGLE_PRESSURE_PLATE,
                Material.JUNGLE_SAPLING,
                Material.JUNGLE_SIGN,
                Material.JUNGLE_SLAB,
                Material.JUNGLE_STAIRS,
                Material.JUNGLE_TRAPDOOR,
                Material.JUNGLE_WOOD,
                Material.KELP,
                Material.LADDER,
                Material.LANTERN,
                Material.LAPIS_BLOCK,
                Material.LAPIS_LAZULI,
                Material.LAVA_BUCKET,
                Material.LEATHER,
                Material.LEATHER_BOOTS,
                Material.LEATHER_CHESTPLATE,
                Material.LEATHER_HELMET,
                Material.LEATHER_HORSE_ARMOR,
                Material.LEATHER_LEGGINGS,
                Material.LECTERN,
                Material.LEVER,
                Material.LIGHT_BLUE_BANNER,
                Material.LIGHT_BLUE_BED,
                Material.LIGHT_BLUE_CARPET,
                Material.LIGHT_BLUE_CONCRETE,
                Material.LIGHT_BLUE_CONCRETE_POWDER,
                Material.LIGHT_BLUE_DYE,
                Material.LIGHT_BLUE_GLAZED_TERRACOTTA,
                Material.LIGHT_BLUE_STAINED_GLASS,
                Material.LIGHT_BLUE_STAINED_GLASS_PANE,
                Material.LIGHT_BLUE_TERRACOTTA,
                Material.LIGHT_BLUE_WOOL,
                Material.LIGHT_GRAY_BANNER,
                Material.LIGHT_GRAY_BED,
                Material.LIGHT_GRAY_CARPET,
                Material.LIGHT_GRAY_CONCRETE,
                Material.LIGHT_GRAY_CONCRETE_POWDER,
                Material.LIGHT_GRAY_DYE,
                Material.LIGHT_GRAY_GLAZED_TERRACOTTA,
                Material.LIGHT_GRAY_STAINED_GLASS,
                Material.LIGHT_GRAY_STAINED_GLASS_PANE,
                Material.LIGHT_GRAY_TERRACOTTA,
                Material.LIGHT_GRAY_WOOL,
                Material.LIGHT_WEIGHTED_PRESSURE_PLATE,
                Material.LIGHTNING_ROD,
                Material.LILAC,
                Material.LILY_OF_THE_VALLEY,
                Material.MAGENTA_BANNER,
                Material.MAGENTA_BED,
                Material.MAGENTA_CARPET,
                Material.MAGENTA_CONCRETE,
                Material.MAGENTA_CONCRETE_POWDER,
                Material.MAGENTA_DYE,
                Material.MAGENTA_GLAZED_TERRACOTTA,
                Material.MAGENTA_STAINED_GLASS,
                Material.MAGENTA_STAINED_GLASS_PANE,
                Material.MAGENTA_TERRACOTTA,
                Material.MAGENTA_WOOL,
                Material.MAGMA_BLOCK,
                Material.MAP,
                Material.MELON,
                Material.MELON_SEEDS,
                Material.MELON_SLICE,
                Material.MILK_BUCKET,
                Material.MINECART,
                Material.MOSSY_COBBLESTONE,
                Material.MOSSY_COBBLESTONE_SLAB,
                Material.MOSSY_COBBLESTONE_STAIRS,
                Material.MOSSY_COBBLESTONE_WALL,
                Material.MOSSY_STONE_BRICK_SLAB,
                Material.MOSSY_STONE_BRICK_STAIRS,
                Material.MOSSY_STONE_BRICK_WALL,
                Material.MOSSY_STONE_BRICKS,
                Material.MUD,
                Material.MUD_BRICK_SLAB,
                Material.MUD_BRICK_STAIRS,
                Material.MUD_BRICK_WALL,
                Material.MUD_BRICKS,
                Material.MUTTON,
                Material.NETHERRACK,
                Material.NOTE_BLOCK,
                Material.OAK_BOAT,
                Material.OAK_BUTTON,
                Material.OAK_CHEST_BOAT,
                Material.OAK_DOOR,
                Material.OAK_FENCE,
                Material.OAK_FENCE_GATE,
                Material.OAK_HANGING_SIGN,
                Material.OAK_LEAVES,
                Material.OAK_LOG,
                Material.OAK_PLANKS,
                Material.OAK_PRESSURE_PLATE,
                Material.OAK_SAPLING,
                Material.OAK_SIGN,
                Material.OAK_SLAB,
                Material.OAK_STAIRS,
                Material.OAK_TRAPDOOR,
                Material.OAK_WOOD,
                Material.OBSIDIAN,
                Material.ORANGE_BANNER,
                Material.ORANGE_BED,
                Material.ORANGE_CARPET,
                Material.ORANGE_CONCRETE,
                Material.ORANGE_CONCRETE_POWDER,
                Material.ORANGE_DYE,
                Material.ORANGE_GLAZED_TERRACOTTA,
                Material.ORANGE_STAINED_GLASS,
                Material.ORANGE_STAINED_GLASS_PANE,
                Material.ORANGE_TERRACOTTA,
                Material.ORANGE_WOOL,
                Material.OXEYE_DAISY,
                Material.PACKED_MUD,
                Material.PAINTING,
                Material.PAPER,
                Material.PEONY,
                Material.PINK_BANNER,
                Material.PINK_BED,
                Material.PINK_CARPET,
                Material.PINK_CONCRETE,
                Material.PINK_CONCRETE_POWDER,
                Material.PINK_DYE,
                Material.PINK_GLAZED_TERRACOTTA,
                Material.PINK_STAINED_GLASS,
                Material.PINK_STAINED_GLASS_PANE,
                Material.PINK_TERRACOTTA,
                Material.PINK_WOOL,
                Material.PISTON,
                Material.POLISHED_ANDESITE,
                Material.POLISHED_ANDESITE_SLAB,
                Material.POLISHED_ANDESITE_STAIRS,
                Material.POLISHED_DEEPSLATE,
                Material.POLISHED_DEEPSLATE_SLAB,
                Material.POLISHED_DEEPSLATE_STAIRS,
                Material.POLISHED_DEEPSLATE_WALL,
                Material.POLISHED_DIORITE,
                Material.POLISHED_DIORITE_SLAB,
                Material.POLISHED_DIORITE_STAIRS,
                Material.POLISHED_GRANITE,
                Material.POLISHED_GRANITE_SLAB,
                Material.POLISHED_GRANITE_STAIRS,
                Material.POLISHED_TUFF,
                Material.POLISHED_TUFF_SLAB,
                Material.POLISHED_TUFF_STAIRS,
                Material.POLISHED_TUFF_WALL,
                Material.POPPY,
                Material.PORKCHOP,
                Material.POTATO,
                Material.POWERED_RAIL,
                Material.PUMPKIN,
                Material.PUMPKIN_PIE,
                Material.PUMPKIN_SEEDS,
                Material.PURPLE_BANNER,
                Material.PURPLE_BED,
                Material.PURPLE_CARPET,
                Material.PURPLE_CONCRETE,
                Material.PURPLE_CONCRETE_POWDER,
                Material.PURPLE_DYE,
                Material.PURPLE_GLAZED_TERRACOTTA,
                Material.PURPLE_STAINED_GLASS,
                Material.PURPLE_STAINED_GLASS_PANE,
                Material.PURPLE_TERRACOTTA,
                Material.PURPLE_WOOL,
                Material.RAIL,
                Material.RAW_COPPER,
                Material.RAW_COPPER_BLOCK,
                Material.RAW_GOLD,
                Material.RAW_GOLD_BLOCK,
                Material.RAW_IRON,
                Material.RAW_IRON_BLOCK,
                Material.RED_BANNER,
                Material.RED_BED,
                Material.RED_CARPET,
                Material.RED_CONCRETE,
                Material.RED_CONCRETE_POWDER,
                Material.RED_DYE,
                Material.RED_GLAZED_TERRACOTTA,
                Material.RED_MUSHROOM,
                Material.RED_STAINED_GLASS,
                Material.RED_STAINED_GLASS_PANE,
                Material.RED_TERRACOTTA,
                Material.RED_WOOL,
                Material.REDSTONE,
                Material.REDSTONE_BLOCK,
                Material.REDSTONE_TORCH,
                Material.REPEATER,
                Material.ROSE_BUSH,
                Material.ROTTEN_FLESH,
                Material.SALMON,
                Material.SALMON_BUCKET,
                Material.SAND,
                Material.SANDSTONE,
                Material.SANDSTONE_SLAB,
                Material.SANDSTONE_STAIRS,
                Material.SANDSTONE_WALL,
                Material.SEAGRASS,
                Material.SHEARS,
                Material.SHIELD,
                Material.SHORT_GRASS,
                Material.SMITHING_TABLE,
                Material.SMOKER,
                Material.SMOOTH_BASALT,
                Material.SMOOTH_SANDSTONE,
                Material.SMOOTH_SANDSTONE_SLAB,
                Material.SMOOTH_SANDSTONE_STAIRS,
                Material.SMOOTH_STONE,
                Material.SMOOTH_STONE_SLAB,
                Material.SNOW,
                Material.SNOW_BLOCK,
                Material.SNOWBALL,
                Material.SPRUCE_BOAT,
                Material.SPRUCE_BUTTON,
                Material.SPRUCE_CHEST_BOAT,
                Material.SPRUCE_DOOR,
                Material.SPRUCE_FENCE,
                Material.SPRUCE_FENCE_GATE,
                Material.SPRUCE_HANGING_SIGN,
                Material.SPRUCE_LEAVES,
                Material.SPRUCE_LOG,
                Material.SPRUCE_PLANKS,
                Material.SPRUCE_PRESSURE_PLATE,
                Material.SPRUCE_SAPLING,
                Material.SPRUCE_SIGN,
                Material.SPRUCE_SLAB,
                Material.SPRUCE_STAIRS,
                Material.SPRUCE_TRAPDOOR,
                Material.SPRUCE_WOOD,
                Material.SPYGLASS,
                Material.STICK,
                Material.STONE,
                Material.STONE_AXE,
                Material.STONE_BRICK_SLAB,
                Material.STONE_BRICK_STAIRS,
                Material.STONE_BRICK_WALL,
                Material.STONE_BRICKS,
                Material.STONE_BUTTON,
                Material.STONE_HOE,
                Material.STONE_PICKAXE,
                Material.STONE_PRESSURE_PLATE,
                Material.STONE_SHOVEL,
                Material.STONE_SLAB,
                Material.STONE_STAIRS,
                Material.STONE_SWORD,
                Material.STONECUTTER,
                Material.STRIPPED_ACACIA_LOG,
                Material.STRIPPED_ACACIA_WOOD,
                Material.STRIPPED_BAMBOO_BLOCK,
                Material.STRIPPED_BIRCH_LOG,
                Material.STRIPPED_BIRCH_WOOD,
                Material.STRIPPED_DARK_OAK_LOG,
                Material.STRIPPED_DARK_OAK_WOOD,
                Material.STRIPPED_JUNGLE_LOG,
                Material.STRIPPED_JUNGLE_WOOD,
                Material.STRIPPED_OAK_LOG,
                Material.STRIPPED_OAK_WOOD,
                Material.STRIPPED_SPRUCE_LOG,
                Material.STRIPPED_SPRUCE_WOOD,
                Material.SUGAR,
                Material.SUGAR_CANE,
                Material.SUNFLOWER,
                Material.SUSPICIOUS_STEW,
                Material.SWEET_BERRIES,
                Material.TARGET,
                Material.TERRACOTTA,
                Material.TINTED_GLASS,
                Material.TORCH,
                Material.TRAPPED_CHEST,
                Material.TRIPWIRE_HOOK,
                Material.TUFF,
                Material.TUFF_BRICK_SLAB,
                Material.TUFF_BRICK_STAIRS,
                Material.TUFF_BRICK_WALL,
                Material.TUFF_BRICKS,
                Material.TUFF_SLAB,
                Material.TUFF_STAIRS,
                Material.TUFF_WALL,
                Material.VINE,
                Material.WATER_BUCKET,
                Material.WHEAT,
                Material.WHEAT_SEEDS,
                Material.WHITE_BANNER,
                Material.WHITE_BED,
                Material.WHITE_CARPET,
                Material.WHITE_CONCRETE,
                Material.WHITE_CONCRETE_POWDER,
                Material.WHITE_DYE,
                Material.WHITE_GLAZED_TERRACOTTA,
                Material.WHITE_STAINED_GLASS,
                Material.WHITE_STAINED_GLASS_PANE,
                Material.WHITE_TERRACOTTA,
                Material.WHITE_WOOL,
                Material.WOLF_ARMOR,
                Material.WOODEN_AXE,
                Material.WOODEN_HOE,
                Material.WOODEN_PICKAXE,
                Material.WOODEN_SHOVEL,
                Material.WOODEN_SWORD,
                Material.WRITABLE_BOOK,
                Material.WRITTEN_BOOK,
                Material.YELLOW_BANNER,
                Material.YELLOW_BED,
                Material.YELLOW_CARPET,
                Material.YELLOW_CONCRETE,
                Material.YELLOW_CONCRETE_POWDER,
                Material.YELLOW_DYE,
                Material.YELLOW_GLAZED_TERRACOTTA,
                Material.YELLOW_STAINED_GLASS,
                Material.YELLOW_STAINED_GLASS_PANE,
                Material.YELLOW_TERRACOTTA,
                Material.YELLOW_WOOL
        ));

        State.MID.setItems(List.of(
                Material.ALLIUM,
                Material.ANVIL,
                Material.AXOLOTL_BUCKET,
                Material.AZALEA,
                Material.AZALEA_LEAVES,
                Material.BASALT,
                Material.BEETROOT,
                Material.BEETROOT_SEEDS,
                Material.BEETROOT_SOUP,
                Material.BIG_DRIPLEAF,
                Material.BLACKSTONE,
                Material.BLACKSTONE_SLAB,
                Material.BLACKSTONE_STAIRS,
                Material.BLACKSTONE_WALL,
                Material.BLUE_ORCHID,
                Material.BOW,
                Material.BREWING_STAND,
                Material.CACTUS,
                Material.CAKE,
                Material.CHERRY_BOAT,
                Material.CHERRY_BUTTON,
                Material.CHERRY_CHEST_BOAT,
                Material.CHERRY_DOOR,
                Material.CHERRY_FENCE,
                Material.CHERRY_FENCE_GATE,
                Material.CHERRY_HANGING_SIGN,
                Material.CHERRY_LEAVES,
                Material.CHERRY_LOG,
                Material.CHERRY_PLANKS,
                Material.CHERRY_PRESSURE_PLATE,
                Material.CHERRY_SAPLING,
                Material.CHERRY_SIGN,
                Material.CHERRY_SLAB,
                Material.CHERRY_STAIRS,
                Material.CHERRY_TRAPDOOR,
                Material.CHERRY_WOOD,
                Material.CHIPPED_ANVIL,
                Material.CHISELED_NETHER_BRICKS,
                Material.CHISELED_POLISHED_BLACKSTONE,
                Material.CHISELED_QUARTZ_BLOCK,
                Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.COBWEB,
                Material.COMPARATOR,
                Material.COOKED_RABBIT,
                Material.CRACKED_NETHER_BRICKS,
                Material.CRACKED_POLISHED_BLACKSTONE_BRICKS,
                Material.CRIMSON_BUTTON,
                Material.CRIMSON_DOOR,
                Material.CRIMSON_FENCE,
                Material.CRIMSON_FENCE_GATE,
                Material.CRIMSON_FUNGUS,
                Material.CRIMSON_HANGING_SIGN,
                Material.CRIMSON_HYPHAE,
                Material.CRIMSON_NYLIUM,
                Material.CRIMSON_PLANKS,
                Material.CRIMSON_PRESSURE_PLATE,
                Material.CRIMSON_ROOTS,
                Material.CRIMSON_SIGN,
                Material.CRIMSON_SLAB,
                Material.CRIMSON_STAIRS,
                Material.CRIMSON_STEM,
                Material.CRIMSON_TRAPDOOR,
                Material.CRYING_OBSIDIAN,
                Material.CROSSBOW,
                Material.CYAN_BANNER,
                Material.CYAN_BED,
                Material.CYAN_CARPET,
                Material.CYAN_CONCRETE,
                Material.CYAN_CONCRETE_POWDER,
                Material.CYAN_DYE,
                Material.CYAN_GLAZED_TERRACOTTA,
                Material.CYAN_STAINED_GLASS,
                Material.CYAN_STAINED_GLASS_PANE,
                Material.CYAN_TERRACOTTA,
                Material.CYAN_WOOL,
                Material.DAMAGED_ANVIL,
                Material.DARK_PRISMARINE,
                Material.DARK_PRISMARINE_SLAB,
                Material.DARK_PRISMARINE_STAIRS,
                Material.DAYLIGHT_DETECTOR,
                Material.DEAD_BRAIN_CORAL_BLOCK,
                Material.DEAD_BUBBLE_CORAL_BLOCK,
                Material.DEAD_BUSH,
                Material.DEAD_FIRE_CORAL_BLOCK,
                Material.DEAD_HORN_CORAL_BLOCK,
                Material.DEAD_TUBE_CORAL_BLOCK,
                Material.DIAMOND_BLOCK,
                Material.DIAMOND_CHESTPLATE,
                Material.DIAMOND_HELMET,
                Material.DIAMOND_HORSE_ARMOR,
                Material.DIAMOND_LEGGINGS,
                Material.DISPENSER,
                Material.DRIPSTONE_BLOCK,
                Material.EGG,
                Material.ENCHANTING_TABLE,
                Material.ENDER_EYE,
                Material.ENDER_PEARL,
                Material.EMERALD_BLOCK,
                Material.FERMENTED_SPIDER_EYE,
                Material.FIRE_CHARGE,
                Material.FISHING_ROD,
                Material.FLOWERING_AZALEA,
                Material.FLOWERING_AZALEA_LEAVES,
                Material.GHAST_TEAR,
                Material.GLOW_BERRIES,
                Material.GLOWSTONE,
                Material.GLOWSTONE_DUST,
                Material.GOLDEN_HORSE_ARMOR,
                Material.GREEN_BANNER,
                Material.GREEN_BED,
                Material.GREEN_CARPET,
                Material.GREEN_CONCRETE,
                Material.GREEN_CONCRETE_POWDER,
                Material.GREEN_DYE,
                Material.GREEN_GLAZED_TERRACOTTA,
                Material.GREEN_STAINED_GLASS,
                Material.GREEN_STAINED_GLASS_PANE,
                Material.GREEN_TERRACOTTA,
                Material.GREEN_WOOL,
                Material.HANGING_ROOTS,
                Material.HEART_OF_THE_SEA,
                Material.IRON_HORSE_ARMOR,
                Material.KNOWLEDGE_BOOK,
                Material.LEAD,
                Material.LILY_PAD,
                Material.LIME_BANNER,
                Material.LIME_BED,
                Material.LIME_CARPET,
                Material.LIME_CONCRETE,
                Material.LIME_CONCRETE_POWDER,
                Material.LIME_DYE,
                Material.LIME_GLAZED_TERRACOTTA,
                Material.LIME_STAINED_GLASS,
                Material.LIME_STAINED_GLASS_PANE,
                Material.LIME_TERRACOTTA,
                Material.LIME_WOOL,
                Material.LOOM,
                Material.MAGMA_CREAM,
                Material.MANGROVE_BOAT,
                Material.MANGROVE_BUTTON,
                Material.MANGROVE_CHEST_BOAT,
                Material.MANGROVE_DOOR,
                Material.MANGROVE_FENCE,
                Material.MANGROVE_FENCE_GATE,
                Material.MANGROVE_HANGING_SIGN,
                Material.MANGROVE_LEAVES,
                Material.MANGROVE_LOG,
                Material.MANGROVE_PLANKS,
                Material.MANGROVE_PRESSURE_PLATE,
                Material.MANGROVE_PROPAGULE,
                Material.MANGROVE_ROOTS,
                Material.MANGROVE_SIGN,
                Material.MANGROVE_SLAB,
                Material.MANGROVE_STAIRS,
                Material.MANGROVE_TRAPDOOR,
                Material.MANGROVE_WOOD,
                Material.MOSS_BLOCK,
                Material.MOSS_CARPET,
                Material.MUDDY_MANGROVE_ROOTS,
                Material.MUSHROOM_STEW,
                Material.MUSIC_DISC_PIGSTEP,
                Material.NAME_TAG,
                Material.NAUTILUS_SHELL,
                Material.NETHER_BRICK,
                Material.NETHER_BRICK_FENCE,
                Material.NETHER_BRICK_SLAB,
                Material.NETHER_BRICK_STAIRS,
                Material.NETHER_BRICK_WALL,
                Material.NETHER_BRICKS,
                Material.NETHER_SPROUTS,
                Material.NETHER_WART,
                Material.NETHER_WART_BLOCK,
                Material.OBSERVER,
                Material.ORANGE_TULIP,
                Material.PINK_PETALS,
                Material.PINK_TULIP,
                Material.POINTED_DRIPSTONE,
                Material.POISONOUS_POTATO,
                Material.POLISHED_BASALT,
                Material.POLISHED_BLACKSTONE,
                Material.POLISHED_BLACKSTONE_BRICK_SLAB,
                Material.POLISHED_BLACKSTONE_BRICK_STAIRS,
                Material.POLISHED_BLACKSTONE_BRICK_WALL,
                Material.POLISHED_BLACKSTONE_BRICKS,
                Material.POLISHED_BLACKSTONE_BUTTON,
                Material.POLISHED_BLACKSTONE_PRESSURE_PLATE,
                Material.POLISHED_BLACKSTONE_SLAB,
                Material.POLISHED_BLACKSTONE_STAIRS,
                Material.POLISHED_BLACKSTONE_WALL,
                Material.POTION,
                Material.POWDER_SNOW_BUCKET,
                Material.PRISMARINE,
                Material.PRISMARINE_BRICK_SLAB,
                Material.PRISMARINE_BRICK_STAIRS,
                Material.PRISMARINE_BRICKS,
                Material.PRISMARINE_CRYSTALS,
                Material.PRISMARINE_SHARD,
                Material.PRISMARINE_SLAB,
                Material.PRISMARINE_STAIRS,
                Material.PRISMARINE_WALL,
                Material.PUFFERFISH,
                Material.PUFFERFISH_BUCKET,
                Material.QUARTZ,
                Material.QUARTZ_BLOCK,
                Material.QUARTZ_BRICKS,
                Material.QUARTZ_PILLAR,
                Material.QUARTZ_SLAB,
                Material.QUARTZ_STAIRS,
                Material.RABBIT,
                Material.RABBIT_FOOT,
                Material.RABBIT_HIDE,
                Material.RABBIT_STEW,
                Material.RED_NETHER_BRICK_SLAB,
                Material.RED_NETHER_BRICK_STAIRS,
                Material.RED_NETHER_BRICK_WALL,
                Material.RED_NETHER_BRICKS,
                Material.RED_TULIP,
                Material.REDSTONE_LAMP,
                Material.ROOTED_DIRT,
                Material.SADDLE,
                Material.SCAFFOLDING,
                Material.SEA_LANTERN,
                Material.SEA_PICKLE,
                Material.SHROOMLIGHT,
                Material.SLIME_BALL,
                Material.SMALL_DRIPLEAF,
                Material.SMOOTH_QUARTZ,
                Material.SMOOTH_QUARTZ_SLAB,
                Material.SMOOTH_QUARTZ_STAIRS,
                Material.SOUL_CAMPFIRE,
                Material.SOUL_LANTERN,
                Material.SOUL_SAND,
                Material.SOUL_SOIL,
                Material.SOUL_TORCH,
                Material.SPECTRAL_ARROW,
                Material.SPIDER_EYE,
                Material.SPONGE,
                Material.SPORE_BLOSSOM,
                Material.STICKY_PISTON,
                Material.STRING,
                Material.STRIPPED_CHERRY_LOG,
                Material.STRIPPED_CHERRY_WOOD,
                Material.STRIPPED_CRIMSON_HYPHAE,
                Material.STRIPPED_CRIMSON_STEM,
                Material.STRIPPED_MANGROVE_LOG,
                Material.STRIPPED_MANGROVE_WOOD,
                Material.STRIPPED_WARPED_HYPHAE,
                Material.STRIPPED_WARPED_STEM,
                Material.TNT,
                Material.TNT_MINECART,
                Material.TROPICAL_FISH,
                Material.TROPICAL_FISH_BUCKET,
                Material.TWISTING_VINES,
                Material.WARPED_BUTTON,
                Material.WARPED_DOOR,
                Material.WARPED_FENCE,
                Material.WARPED_FENCE_GATE,
                Material.WARPED_FUNGUS,
                Material.WARPED_FUNGUS_ON_A_STICK,
                Material.WARPED_HANGING_SIGN,
                Material.WARPED_HYPHAE,
                Material.WARPED_NYLIUM,
                Material.WARPED_PLANKS,
                Material.WARPED_PRESSURE_PLATE,
                Material.WARPED_ROOTS,
                Material.WARPED_SIGN,
                Material.WARPED_SLAB,
                Material.WARPED_STAIRS,
                Material.WARPED_STEM,
                Material.WARPED_TRAPDOOR,
                Material.WARPED_WART_BLOCK,
                Material.WEEPING_VINES,
                Material.WET_SPONGE,
                Material.WHITE_TULIP,
                Material.WITHER_ROSE // Trial Chambers Locator
        ));

        State.LATE.setItems(List.of(
                Material.AMETHYST_CLUSTER,
                Material.ANCIENT_DEBRIS,
                Material.ANGLER_POTTERY_SHERD,
                Material.ARCHER_POTTERY_SHERD,
                Material.BEE_NEST,
                Material.BEEHIVE,
                Material.BLACK_CANDLE,
                Material.BLACK_SHULKER_BOX,
                Material.BLADE_POTTERY_SHERD,
                Material.BLAZE_POWDER,
                Material.BLAZE_ROD,
                Material.BLUE_CANDLE,
                Material.BLUE_ICE,
                Material.BLUE_SHULKER_BOX,
                Material.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.BRAIN_CORAL,
                Material.BRAIN_CORAL_BLOCK,
                Material.BRAIN_CORAL_FAN,
                Material.BREEZE_ROD,
                Material.BROWN_CANDLE,
                Material.BROWN_MUSHROOM_BLOCK,
                Material.BROWN_SHULKER_BOX,
                Material.BUBBLE_CORAL,
                Material.BUBBLE_CORAL_BLOCK,
                Material.BUBBLE_CORAL_FAN,
                Material.CALIBRATED_SCULK_SENSOR,
                Material.CANDLE,
                Material.CHAINMAIL_BOOTS,
                Material.CHAINMAIL_CHESTPLATE,
                Material.CHAINMAIL_HELMET,
                Material.CHAINMAIL_LEGGINGS,
                Material.CHISELED_RED_SANDSTONE,
                Material.CHORUS_FLOWER,
                Material.CHORUS_FRUIT,
                Material.COAL_ORE,
                Material.COPPER_BULB,
                Material.COPPER_ORE,
                Material.CUT_RED_SANDSTONE,
                Material.CUT_RED_SANDSTONE_SLAB,
                Material.CYAN_CANDLE,
                Material.CYAN_SHULKER_BOX,
                Material.DEAD_BRAIN_CORAL,
                Material.DEAD_BRAIN_CORAL_FAN,
                Material.DEAD_BUBBLE_CORAL,
                Material.DEAD_BUBBLE_CORAL_FAN,
                Material.DEAD_FIRE_CORAL,
                Material.DEAD_FIRE_CORAL_FAN,
                Material.DEAD_HORN_CORAL,
                Material.DEAD_HORN_CORAL_FAN,
                Material.DEAD_TUBE_CORAL,
                Material.DEAD_TUBE_CORAL_FAN,
                Material.DECORATED_POT,
                Material.DEEPSLATE_COAL_ORE,
                Material.DEEPSLATE_COPPER_ORE,
                Material.DEEPSLATE_DIAMOND_ORE,
                Material.DEEPSLATE_EMERALD_ORE,
                Material.DEEPSLATE_GOLD_ORE,
                Material.DEEPSLATE_IRON_ORE,
                Material.DEEPSLATE_LAPIS_ORE,
                Material.DEEPSLATE_REDSTONE_ORE,
                Material.DIAMOND_ORE,
                Material.DISC_FRAGMENT_5,
                Material.DRAGON_HEAD,
                Material.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.ECHO_SHARD,
                Material.ELYTRA,
                Material.EMERALD_ORE,
                Material.ENCHANTED_BOOK,
                Material.ENCHANTED_GOLDEN_APPLE,
                Material.END_CRYSTAL,
                Material.END_ROD,
                Material.END_STONE,
                Material.END_STONE_BRICK_SLAB,
                Material.END_STONE_BRICK_STAIRS,
                Material.END_STONE_BRICK_WALL,
                Material.END_STONE_BRICKS,
                Material.ENDER_CHEST,
                Material.EXPERIENCE_BOTTLE,
                Material.EXPLORER_POTTERY_SHERD,
                Material.EXPOSED_CHISELED_COPPER,
                Material.EXPOSED_COPPER_BULB,
                Material.EXPOSED_COPPER_DOOR,
                Material.EXPOSED_COPPER_GRATE,
                Material.EXPOSED_CUT_COPPER,
                Material.EXPOSED_CUT_COPPER_SLAB,
                Material.EXPOSED_CUT_COPPER_STAIRS,
                Material.FIRE_CORAL,
                Material.FIRE_CORAL_BLOCK,
                Material.FIRE_CORAL_FAN,
                Material.FLOW_BANNER_PATTERN,
                Material.FLOW_POTTERY_SHERD,
                Material.GILDED_BLACKSTONE,
                Material.GLOBE_BANNER_PATTERN,
                Material.GOAT_HORN,
                Material.GOLD_ORE,
                Material.GRASS_BLOCK,
                Material.GRAY_CANDLE,
                Material.GRAY_SHULKER_BOX,
                Material.GREEN_CANDLE,
                Material.GREEN_SHULKER_BOX,
                Material.GUSTER_BANNER_PATTERN,
                Material.GUSTER_POTTERY_SHERD,
                Material.HONEY_BLOCK,
                Material.HONEY_BOTTLE,
                Material.HONEYCOMB,
                Material.HONEYCOMB_BLOCK,
                Material.HORN_CORAL,
                Material.HORN_CORAL_BLOCK,
                Material.HORN_CORAL_FAN,
                Material.ICE,
                Material.IRON_ORE,
                Material.LAPIS_ORE,
                Material.LARGE_AMETHYST_BUD,
                Material.LARGE_FERN,
                Material.LIGHT_BLUE_CANDLE,
                Material.LIGHT_BLUE_SHULKER_BOX,
                Material.LIGHT_GRAY_CANDLE,
                Material.LIGHT_GRAY_SHULKER_BOX,
                Material.LIME_CANDLE,
                Material.LIME_SHULKER_BOX,
                Material.LODESTONE,
                Material.MAGENTA_CANDLE,
                Material.MAGENTA_SHULKER_BOX,
                Material.MEDIUM_AMETHYST_BUD,
                Material.MINER_POTTERY_SHERD,
                Material.MOJANG_BANNER_PATTERN,
                Material.MOURNER_POTTERY_SHERD,
                Material.MUSHROOM_STEM,
                Material.MUSIC_DISC_13,
                Material.MUSIC_DISC_CAT,
                Material.MUSIC_DISC_CREATOR,
                Material.MUSIC_DISC_CREATOR_MUSIC_BOX,
                Material.MUSIC_DISC_OTHERSIDE,
                Material.MUSIC_DISC_PRECIPICE,
                Material.MYCELIUM,
                Material.NETHER_GOLD_ORE,
                Material.NETHER_QUARTZ_ORE,
                Material.NETHERITE_AXE,
                Material.NETHERITE_BLOCK,
                Material.NETHERITE_BOOTS,
                Material.NETHERITE_CHESTPLATE,
                Material.NETHERITE_HELMET,
                Material.NETHERITE_HOE,
                Material.NETHERITE_INGOT,
                Material.NETHERITE_LEGGINGS,
                Material.NETHERITE_PICKAXE,
                Material.NETHERITE_SCRAP,
                Material.NETHERITE_SHOVEL,
                Material.NETHERITE_SWORD,
                Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE,
                Material.OMINOUS_BOTTLE,
                Material.OMINOUS_TRIAL_KEY,
                Material.ORANGE_CANDLE,
                Material.ORANGE_SHULKER_BOX,
                Material.OXIDIZED_CHISELED_COPPER,
                Material.OXIDIZED_COPPER_BULB,
                Material.OXIDIZED_COPPER_DOOR,
                Material.OXIDIZED_COPPER_GRATE,
                Material.OXIDIZED_CUT_COPPER,
                Material.OXIDIZED_CUT_COPPER_SLAB,
                Material.OXIDIZED_CUT_COPPER_STAIRS,
                Material.PACKED_ICE,
                Material.PIGLIN_BANNER_PATTERN,
                Material.PINK_CANDLE,
                Material.PINK_SHULKER_BOX,
                Material.PLENTY_POTTERY_SHERD,
                Material.PODZOL,
                Material.POPPED_CHORUS_FRUIT,
                Material.PRIZE_POTTERY_SHERD,
                Material.PURPLE_CANDLE,
                Material.PURPLE_SHULKER_BOX,
                Material.PURPUR_BLOCK,
                Material.PURPUR_PILLAR,
                Material.PURPUR_SLAB,
                Material.PURPUR_STAIRS,
                Material.RED_CANDLE,
                Material.RED_MUSHROOM_BLOCK,
                Material.RED_SAND,
                Material.RED_SANDSTONE,
                Material.RED_SANDSTONE_SLAB,
                Material.RED_SANDSTONE_STAIRS,
                Material.RED_SANDSTONE_WALL,
                Material.RED_SHULKER_BOX,
                Material.REDSTONE_ORE,
                Material.RESPAWN_ANCHOR,
                Material.RIB_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.SCRAPE_POTTERY_SHERD,
                Material.SCULK,
                Material.SCULK_CATALYST,
                Material.SCULK_SENSOR,
                Material.SCULK_SHRIEKER,
                Material.SCULK_VEIN,
                Material.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.SHELTER_POTTERY_SHERD,
                Material.SHULKER_BOX,
                Material.SHULKER_SHELL,
                Material.SKULL_BANNER_PATTERN,
                Material.SKULL_POTTERY_SHERD,
                Material.SLIME_BLOCK,
                Material.SMALL_AMETHYST_BUD,
                Material.SMOOTH_RED_SANDSTONE,
                Material.SMOOTH_RED_SANDSTONE_SLAB,
                Material.SMOOTH_RED_SANDSTONE_STAIRS,
                Material.SNIFFER_EGG,
                Material.SNORT_POTTERY_SHERD,
                Material.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.SPLASH_POTION,
                Material.TALL_GRASS,
                Material.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.TIPPED_ARROW,
                Material.TOTEM_OF_UNDYING,
                Material.TRIAL_KEY,
                Material.TRIDENT,
                Material.TUBE_CORAL,
                Material.TUBE_CORAL_BLOCK,
                Material.TUBE_CORAL_FAN,
                Material.VEX_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.WARD_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.WAXED_CHISELED_COPPER,
                Material.WAXED_COPPER_BLOCK,
                Material.WAXED_COPPER_BULB,
                Material.WAXED_COPPER_DOOR,
                Material.WAXED_COPPER_GRATE,
                Material.WAXED_CUT_COPPER,
                Material.WAXED_CUT_COPPER_SLAB,
                Material.WAXED_CUT_COPPER_STAIRS,
                Material.WAXED_EXPOSED_CHISELED_COPPER,
                Material.WAXED_EXPOSED_COPPER_BULB,
                Material.WAXED_EXPOSED_COPPER_DOOR,
                Material.WAXED_EXPOSED_COPPER_GRATE,
                Material.WAXED_EXPOSED_CUT_COPPER,
                Material.WAXED_EXPOSED_CUT_COPPER_SLAB,
                Material.WAXED_EXPOSED_CUT_COPPER_STAIRS,
                Material.WAXED_OXIDIZED_CHISELED_COPPER,
                Material.WAXED_OXIDIZED_COPPER_BULB,
                Material.WAXED_OXIDIZED_COPPER_DOOR,
                Material.WAXED_OXIDIZED_COPPER_GRATE,
                Material.WAXED_OXIDIZED_CUT_COPPER,
                Material.WAXED_OXIDIZED_CUT_COPPER_SLAB,
                Material.WAXED_OXIDIZED_CUT_COPPER_STAIRS,
                Material.WAXED_WEATHERED_CHISELED_COPPER,
                Material.WAXED_WEATHERED_COPPER_BULB,
                Material.WAXED_WEATHERED_COPPER_DOOR,
                Material.WAXED_WEATHERED_COPPER_GRATE,
                Material.WAXED_WEATHERED_CUT_COPPER,
                Material.WAXED_WEATHERED_CUT_COPPER_SLAB,
                Material.WAXED_WEATHERED_CUT_COPPER_STAIRS,
                Material.WEATHERED_CHISELED_COPPER,
                Material.WEATHERED_COPPER_BULB,
                Material.WEATHERED_COPPER_DOOR,
                Material.WEATHERED_COPPER_GRATE,
                Material.WEATHERED_CUT_COPPER_STAIRS,
                Material.WAXED_WEATHERED_CUT_COPPER_STAIRS,
                Material.WHITE_CANDLE,
                Material.WHITE_SHULKER_BOX,
                Material.WILD_ARMOR_TRIM_SMITHING_TEMPLATE,
                Material.WIND_CHARGE,
                Material.WITHER_SKELETON_SKULL,
                Material.YELLOW_CANDLE,
                Material.YELLOW_SHULKER_BOX
        ));

        setupStates();
    }

    @Getter
    public enum State {

        EARLY,

        MID,

        LATE,

        ;

        static final State[] VALUES = values();

        @Setter
        private List<Material> items = new ArrayList<>();

        @Setter
        private double unlockedAtPercentage;

    }
}
